services:
  db:
    image: postgres:16-alpine
    container_name: hotel_postgres
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgre_user
      POSTGRES_PASSWORD: "!postgre1234@"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
