spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/hotel_db
    username: ${prod_user}
    password: ${prod_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
logging:
  level:
    com.hotel: WARN
