spring:
  datasource:
    url: jdbc:postgresql://dev-db-host:5432/hotel_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
logging:
  level:
    com.hotel: INFO
