spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgre_user
    password: "!postgre1234@"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: DEBUG
    com.hotel: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
